In [2]:
import numpy as np

In [10]:
salary = [1000,2000,3000]
salary_array = np.array(salary)
salary_array + 1

#ype(salary_array)

array([1001, 2001, 3001])

In [ ]:
countries = ["Nepal","China",21,True]

In [47]:
salary_array = np.array([1000,2000,3000])
print(salary_array.ndim)
print(salary_array.shape)
print(salary_array.size)
print(salary_array[-1])


data = np.array([
    [10,1000],
    [20,2000],
    [30,3000],
    [40,4000],
    [50,2000],
    [60,3000]
])
print(data[:,1])
print(data[:3])
print(data.ndim)
print(data.shape)
print(data[2:4])
print(data.size)
print(data[0,1])

1
(3,)
3
3000
[1000 2000 3000 4000 2000 3000]
[[  10 1000]
 [  20 2000]
 [  30 3000]]
2
(6, 2)
[[  30 3000]
 [  40 4000]]
12
1000


In [21]:
price = np.array([10,20,30])
print(price.dtype)

int64


In [58]:
numbers = np.array([1,2,3,4,5,6,7])
results = numbers*10
#results > 30
results[(results > 30) & (results < 50)]
# print(results)

array([40])

In [60]:
price = np.array([100,200,300])
quantity = np.array([2,4,6])
price * quantity

array([ 200,  800, 1800])

In [76]:
arr = np.array([1,2,3,4,5,6])
arr.shape
# arr.reshape(2,3)
# arr.reshape(3,2)
arr.reshape(3,-1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [75]:
arr2 = np.array([
    [1,2,3],
    [4,5,6]
])
arr2.shape
arr2.reshape(-1)

array([1, 2, 3, 4, 5, 6])