In [3]:
import pandas as pd
import numpy as np

data = pd.read_csv("datasets/daraz_dataset.csv")
data

,OrderID,OrderDate,CustomerName,Age,Gender,District,Category,Product,Quantity,UnitPrice,DiscountPercent,TotalAmount,PaymentMethod,Rating,OrderStatus
0,DZ100001,2026-03-04,Anita Basnet,Nepal,Male,Nepalgunj,Sports,Football,1,48898,10,44008.20,IME Pay,1,Delivered
1,DZ100002,2026-01-07,Pooja Basnet,52,Female,Pokhara,Electronics,Bluetooth Speaker,2,33418,20,53468.80,IME Pay,5,Cancelled
2,DZ100003,2026-03-29,Rohit Basnet,31,Female,Lalitpur,Books,Python Basics,2,46053,15,78290.10,eSewa,4,Delivered
3,DZ100004,2026-04-28,Pooja Sharma,42,Male,Chitwan,Home,Chair,5,17635,0,88175.00,COD,5,Cancelled
4,DZ100005,2026-03-16,Ram Adhikari,32,Male,Dharan,Groceries,Tea,1,3303,5,3137.85,COD,4,Cancelled
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,DZ100496,2026-03-08,Sita Thapa,48,Male,Nepalgunj,Electronics,Smart Watch,3,47942,20,115060.80,eSewa,3,Processing
496,DZ100497,2026-05-10,Ram Adhikari,35,Female,Bhaktapur,Electronics,Power Bank,4,5707,5,21686.60,Card,3,Cancelled
497,DZ100498,2026-06-04,Nabin Shrestha,27,Female,Itahari,Books,Data Science 101,1,48890,0,48890.00,Khalti,3,Shipped
498,DZ100499,2026-01-22,Gita Shrestha,27,Female,Dharan,Beauty,Shampoo,5,2468,10,11106.00,IME Pay,2,Returned


In [4]:
data.head()
data.shape
data.columns
data.dtypes
data["Age"]
data["Age"] = pd.to_numeric(data["Age"],errors = "coerce")

In [5]:
#shortcutt for chnage dtypes all at a time

numeric_columns = [
    "Age",
    "Quantity",
    "UnitPrice",
    "DiscountPercent",
    "TotalAmount",
    "Rating"
]
for  column in numeric_columns:
    data[column] = pd.to_numeric(data[column],errors="coerce")

In [5]:
data.isnull().sum()
data["Quantity"] = data["Quantity"].fillna(data["Quantity"].mean())

In [8]:
features  = ["Age","Quantity","UnitPrice" ,"DiscountPercent"]
target = "TotalAmount"

#super features store garne X , target store garne y bananunu

x = data[features]
y = data[target]

type(x)
type(y)

x = x.to_numpy()
y = y.to_numpy()

type(x)
type(y)

x.shape
x.ndim
x.dtype
x.nbytes

16000

In [9]:
x[:,0]
x[:,3]

array([10., 20., 15.,  0.,  5., 10., 10., 15., 15.,  0., 10.,  5.,  0.,
       10.,  5.,  0.,  5., 15.,  0.,  0., 10.,  0., 20., 10., 10., 20.,
        5., 10., 10.,  0.,  5.,  5., 20., 10., 20., 15., 20., 15.,  0.,
        0., 20., 10.,  0.,  0., 20.,  5.,  5., 15.,  5., 10., 10., 15.,
       15., 20., 20., 15., 10., 20.,  5.,  0., 15., 20.,  0.,  0.,  5.,
        5., 20.,  0., 15., 15., 20., 10.,  0., 15., 10., 15.,  5.,  5.,
       15., 10.,  5.,  0., 10., 15.,  5., 10., 10., 20., 20.,  0.,  0.,
       10.,  0., 20., 10., 15.,  0.,  0.,  0.,  0.,  0., 10., 10.,  0.,
       10., 15., 20.,  5., 20., 20.,  0.,  0.,  5., 10., 15., 20., 10.,
       10., 20., 15., 10., 10., 10., 20., 10., 20., 15.,  5.,  0., 20.,
        5.,  0., 10., 15.,  0., 10., 20., 15.,  5., 15.,  0.,  0.,  5.,
       20., 15.,  5., 20., 20., 20.,  0.,  5.,  0., 15.,  0., 10., 10.,
       20.,  5., 20., 10.,  5., 20., 10.,  5., 20., 10.,  0.,  5.,  0.,
       20., 15., 20., 15.,  5., 15., 20., 10., 15.,  0., 15., 20

In [10]:
# x[x[:,0]>30]

print(np.min(x[:,0]))

nan


In [14]:
age = np.array([10,20,30])
roll_no = np.array([11,22,33])
print(age)
print(roll_no)
# type(age)
students = np.array([
    [20,30,40],
    [10,12,14]
])
print(students)

[10 20 30]
[11 22 33]
[[20 30 40]
 [10 12 14]]


In [25]:
student = np.array([
[12,90],
[14,90],
[16,50]])
print(student)
weights = np.array([
    [10],
    [2]
])
prediction = np.dot(student,weights)
print(prediction)

[[12 90]
 [14 90]
 [16 50]]
[[300]
 [320]
 [260]]
